import { REAL_SOLICITATIONS } from "./solicitations.real";
import { SAMPLE_SOLICITATIONS } from "./solicitations.sample";
import { LISTING_SOLICITATIONS } from "./solicitations.listing";
import { parseSolicitations } from "./sources";
import type { Solicitation, SolicitationInput } from "./types";
import attachmentsJson from "./attachments.json";

interface AttachmentRecord {
  bidPageUrl?: string;
  portalUrl?: string;
  attachments: { label: string; url: string; localPath?: string; bytes?: number; contentType?: string }[];
}
/** Generated by `node scripts/fetch-attachments.mjs`; keyed by solicitation id. */
export const ATTACHMENTS: Record<string, AttachmentRecord> = (attachmentsJson as { records: Record<string, AttachmentRecord> }).records;

function withAttachments(input: SolicitationInput): SolicitationInput {
  const a = ATTACHMENTS[input.id];
  if (!a) return input;
  return { ...input, attachments: a.attachments, portalUrl: a.portalUrl ?? input.portalUrl };
}

export const ALL_SOLICITATION_INPUTS: SolicitationInput[] = [
  ...REAL_SOLICITATIONS,
  ...SAMPLE_SOLICITATIONS,
  ...LISTING_SOLICITATIONS,
].map(withAttachments);

/** The validated, in-memory dataset the app ships with. */
export const SOLICITATIONS: Solicitation[] = parseSolicitations(ALL_SOLICITATION_INPUTS);

export const SOLICITATION_BY_ID: Record<string, Solicitation> = Object.fromEntries(
  SOLICITATIONS.map((s) => [s.id, s]),
);

export function getSolicitation(id: string): Solicitation | undefined {
  return SOLICITATION_BY_ID[id];
}
